const data = () => {
    const senderName = 'Saifudding';

    const users = [
        {
            id: '0e82d2e3-bec8-4647-b0ea-e2004614ec5a',
            name: 'Md Shafayet Maruf',
            image: '../assets/profile-pic.png'
        },
        {
            id: '061d6527-e5e7-477b-a62c-a1957a10fde2',
            name: 'Saifudding',
            image: '../assets/sender-pic.jpg'
        }
    ]

    const firstMessage = {
        sender: '061d6527-e5e7-477b-a62c-a1957a10fde2',
        text: `Hey, I'm a chatbot. Don't expect a real answer from me. \
            I am going to give you arbitrary answers which may or may not help you. \
            So, don't get offended.`,
        status: 'sent'
    }

    const defaultResponse = [
        'Do you know 1+1 = 2',
        `Ever wordered how much data is generated every minute? Over 500 hours of video are uploaded to Youtube, 3.8 million Google searched are conducted, and more than 500,000 tweets are sent, all within just 60 seconds!`,
        `The 'hello' in 'hello world' is not just a greeting; it's a tradition that dates back to the 1970s. The first documented use was in a tutorial for the B programming language by Brian Kernighan, co-creator of the C language.`,
        `Did you know that the world's first computer programmer was Ada Lovelace? She wrote the first algorithm intended for processing on Charles Babbage's Analytical Engine in the mid-1800s.`,
        `Programming languages evolve over time. While Fortran is one of the oldest (from the 1950s), newer languages like Rust are designed with memory safety and performance in mind.`,
        `There are more possible iterations of a game of chess than there are atoms in the observable universe. Computers use sophisticated algorithms to calculate and analyze these possibilities.`,
        `The term "bug" in programming originated in the 1940s when a moth caused a malfunction in the Harvard Mark II computer. Grace Hopper famously "debugged" the system by removing the moth.`,
        `The quicksort algorithm, developed by Tony Hoare in 1960, is known for its efficiency. It's still widely used today and has inspired many variations in sorting algorithms.`,
        `The first video game, "Tennis for Two," was created in 1958 by physicist William Higinbotham. It ran on an analog computer and allowed two players to compete in a simulated tennis match.`,
        `The concept of Object-Oriented Programming (OOP) was introduced in the 1960s. OOP focuses on organizing code into reusable and modular structures, enhancing software development.`,
        `JavaScript, initially created in just ten days by Brendan Eich in 1995, has become one of the most popular programming languages, powering dynamic and interactive web applications.`,
        `Open-source software is pervasive in the programming community. Platforms like GitHub host millions of repositories where developers collaborate on projects, fostering innovation.`,
        `The concept of the Internet of Things (IoT) has transformed the way we interact with the world. From smart homes to wearable devices, programming plays a crucial role in IoT development.`
    ];

    const getAutoGeneratedResponse = (input) => {
        console.log(input.trim().length);
        if (input.trim().length == 0)
            return { sender: '061d6527-e5e7-477b-a62c-a1957a10fde2', text: "I see your message is empty" };
    
        const index = Math.floor(Math.random() * (defaultResponse.length - 1));
        return { sender: '061d6527-e5e7-477b-a62c-a1957a10fde2', text: defaultResponse[index] };
    };

    const getUser = (id) => {
        return users.find(user => user.id === id);
    }

    return {
        defaultResponse,
        firstMessage,
        senderName,
        getAutoGeneratedResponse,
        getUser
    }
};